# Generated by Django 2.0.5 on 2018-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_auto_20180514_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
