# Generated by Django 2.0.5 on 2018-05-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_auto_20180514_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentterm',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
