# Generated by Django 2.0.5 on 2018-05-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_auto_20180514_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentterm',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.Document'),
        ),
        migrations.AlterField(
            model_name='documentterm',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.Term'),
        ),
    ]
